#!/bin/sh -e
# initramfs hook for dell-bootstrap
PREREQS=""
# Output pre-requisites
prereqs()
{
       echo "$PREREQS"
}
case "$1" in
    prereqs)
       prereqs
       exit 0
       ;;
esac
. /usr/share/initramfs-tools/hook-functions
copy_exec /usr/bin/openssl
